### ISSUE TITLE
关于.h5文件

### ISSUE THREAD

**Issue by mumuaa1** [leilin1995/Higher-Resolution-and-Less-Noisy-Seismic-Images-An-Application-of-Generative-Adversarial-Neural-Net#1]
我用test.py生成了.h文件，如何将它们可视化呢，谢谢

**Comment by leilin1995** [comment]
You can find read_h5 function in code/utils.py, which can convert .h5 file to np array, and then visualize it  through Matplotlib or other methods.
I hope it will help you.

**Comment by mumuaa1** [comment]
> 



> 您可以在code/utils.py中找到read_h5函数，它可以将.h5文件转换为np数组，然后通过Matplotlib或其他方法进行可视化。 我希望它会帮助你。

谢谢老师的提示，我将图片显示出来了，比如我看的是case7_crossline_0.h5，感觉就是老师例子的图片一部分，请教一下老师，如何显示成老师例子上面的完整地震数据显示，是不是case7 里面的line0-15可以组成完整的图像呢，还是line加上crossline的0-15,由于我知道的太少，有可能表达让您感觉困惑，麻烦老师了

**Comment by leilin1995** [comment]
抱歉，我不太清楚你的数据是什么形式的，所以很难帮到你。不过，等到这篇文章发表后，我可以将论文中可视化的代码发给你。
