### ISSUE TITLE
训练集的问题

### ISSUE THREAD

**Issue by mumuaa1** [leilin1995/Higher-Resolution-and-Less-Noisy-Seismic-Images-An-Application-of-Generative-Adversarial-Neural-Net#2]
老师你好，我想问一下你的训练集怎么制作的呢，你有原始的数据集吗，就是没有经过高分辨率处理和加噪操作的，想得到你的帮助。谢谢啦。

**Comment by leilin1995** [comment]
你好，数据集是在Wu et al, 2019,2020文章中的地震几何模型构造方法的基础上做了修改通过代码实现的，这部分每个人的实现方法可能会有不同，你可以参考Wu的文章自己进行实现。（1.Building realistic structure models to train convolutional neural networks for seismic structural interpretation
2.FaultSeg3D: Using synthetic data sets to train an end-to-end convolutional neural network for 3D seismic fault segmentation）希望对你有帮助。

**Comment by mumuaa1** [comment]
谢谢老师啦，我在用tesseral画地震记录，就感觉画不出好的效果，我去看看你发的文章。
