### ISSUE TITLE
数据处理问题

### ISSUE THREAD

**Issue by jin-xuebin** [leilin1995/Higher-Resolution-and-Less-Noisy-Seismic-Images-An-Application-of-Generative-Adversarial-Neural-Net#3]
想问一下作者，如何将一个segy文件处理成您所使用的数据呢？真心希望可以得到您的答复，谢谢！

**Comment by leilin1995** [comment]
这里，首先需要用python读取segy数据，可以利用segyio这个包，网络上有教程可以学习。然后将其转化为python数组，之后再根据code/utils/save_h5函数就可以将数据存成示例中的数据格式了。
注意，论文中使用的是2D的方式，读入segy数据后需要提取地震切片，这其中要注意数据的维度问题。

**Comment by jin-xuebin** [comment]
嗯嗯，理解了，谢谢老师的答复。这个程序已经调试成功了，对我的帮助很大，非常感谢老师的分享。




靳雪彬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leilin1995/SeisGAN-Improving-Seismic-Image-Resolution-and-Reducing-Noise"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 上午8:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leilin1995/SeisGAN-Improving-Seismic-Image-Resolution-and-Reducing-Noise] 数据处理问题 (Issue #3)





 
这里，首先需要用python读取segy数据，可以利用segyio这个包，网络上有教程可以学习。然后将其转化为python数组，之后再根据code/utils/save_h5函数就可以将数据存成示例中的数据格式了。
 注意，论文中使用的是2D的方式，读入segy数据后需要提取地震切片，这其中要注意数据的维度问题。
